// Ard Ba'alat Map — Leaflet init, layers, popups.
// Data source: data.json, generated by _map_build/build_map.py.

const map = L.map('map').setView([33.85, 35.85], 9);

L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
  attribution: 'Map data: &copy; OpenStreetMap contributors, SRTM | Map style: &copy; OpenTopoMap (CC-BY-SA)',
  maxZoom: 17
}).addTo(map);

const CATEGORY_STYLES = {
  toponym:              { color: '#7c4dff', label: 'Lebanese Toponyms',            defaultOn: true  },
  phoenician_city:      { color: '#00e5c0', label: 'Phoenician Coastal Cities',    defaultOn: true  },
  in_world_location:    { color: '#f4a261', label: 'In-World Locations',           defaultOn: true  },
  covenant_anchor_city: { color: '#c44536', label: 'Covenant of El Anchor Cities', defaultOn: true  },
  silk_kerkhana_site:   { color: '#b87333', label: 'Silk / Kerkhana Sites',        defaultOn: false },
  massacre_famine_site: { color: '#3a3a3a', label: '1860 Massacres & Great Famine', defaultOn: false }
};

function escapeHtml(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildPopupHTML(loc) {
  let html = '<div class="popup-card">';
  html += `<h3>${escapeHtml(loc.title)}</h3>`;

  if (loc.modern_name || loc.arabic_name || loc.ancient_name) {
    const parts = [];
    if (loc.modern_name) {
      parts.push(`<span>${escapeHtml(loc.modern_name)}</span>`);
    }
    if (loc.arabic_name) {
      parts.push(`<span lang="ar">${escapeHtml(loc.arabic_name)}</span>`);
    }
    if (loc.ancient_name) {
      parts.push(`<span class="ancient">${escapeHtml(loc.ancient_name)}</span>`);
    }
    html += `<p class="names">${parts.join(' / ')}</p>`;
  }

  if (loc.origin && loc.meaning) {
    html += `<p class="etymology"><em>${escapeHtml(loc.origin)}</em>: ${escapeHtml(loc.meaning)}</p>`;
  }

  if (loc.historical_evidence) {
    html += `<p class="evidence">Historical evidence: <strong>${escapeHtml(loc.historical_evidence)}</strong></p>`;
  }

  if (loc.public_description) {
    html += `<p class="description">${escapeHtml(loc.public_description)}</p>`;
  }

  html += '</div>';
  return html;
}

fetch('data.json')
  .then(r => r.json())
  .then(data => {
    const layerGroups = {};
    Object.keys(CATEGORY_STYLES).forEach(cat => {
      layerGroups[cat] = L.layerGroup();
    });

    data.locations.forEach(loc => {
      const style = CATEGORY_STYLES[loc.category];
      if (!style) return;
      const marker = L.circleMarker([loc.lat, loc.lng], {
        radius: 8,
        fillColor: style.color,
        color: '#fff',
        weight: 2,
        opacity: 1,
        fillOpacity: 0.85
      });
      marker.bindPopup(buildPopupHTML(loc));
      layerGroups[loc.category].addLayer(marker);
    });

    Object.entries(layerGroups).forEach(([cat, group]) => {
      if (CATEGORY_STYLES[cat].defaultOn) group.addTo(map);
    });

    const overlayDict = {};
    Object.entries(layerGroups).forEach(([cat, group]) => {
      overlayDict[CATEGORY_STYLES[cat].label] = group;
    });
    L.control.layers(null, overlayDict, { collapsed: false }).addTo(map);
  })
  .catch(err => {
    console.error('Failed to load data.json:', err);
  });
